### PR TITLE
[WIP] lite module

### PR DESCRIPTION
**Pull request by zeke**
@vanessayuenn and I are pairing on adding [GraphQL-backed multi-faceted search to the Electron website](https://github.com/electron/electronjs.org/issues/864), and we're using this module as one of the datasources. The current vanilla `require('repos-using-electron')` is very slow because it's assembling an in-memory object from about 20 thousand files on disk.

To work around this, let's export a "lite" version of the module that only contains a subset of the available data for each repo. Currently this lite version weighs in at just 2MB:

```
$ du -hs lite.json 
2.2M	lite.json
```

@vanessayuenn if you want to give this a try, we can skip publishing to npm for now by installing directly from the repo:

```
npm i electron/repos-using-electron#lite
```

and then require it like this:

```js
const repos = require('repos-using-electron/lite')
```

### CODE REVIEW

**Comment by vanessayuenn** [comment]
@zeke what do you think of unifying the structure of each repo in `repos-using-electron` to be the same as `repository` prop in `electron-npm-packages`? We can re-specify the keys each repo object contains as we need. 

For the purpose of the search function we want to implement, I found this insightful -- [How It Works section on npms.io](https://npms.io/about) -- it talks about how the npm search results are ranked based on a few criteria. I think we should also take those criteria into consideration when deciding which props to keep for the `repo` object.

**Comment by zeke** [comment]
cc @codebytere

**Comment by zeke** [comment]
> we should also take those criteria into consideration when deciding which props to keep for the repo object.

👍 

@andrew and @benjam did some similar work to codify project health/quality for @librariesio: https://docs.libraries.io/overview#sourcerank

Example for `electron`: https://libraries.io/npm/electron/sourcerank

**Comment by zeke** [comment]
There's an API for sourcerank too: https://libraries.io/api/npm/electron/sourcerank?api_key=

```json
{
"basic_info_present": 1,
"repository_present": 1,
"readme_present": 1,
"license_present": 1,
"versions_present": 1,
"follows_semver": 1,
"recent_release": 1,
"not_brand_new": 1,
"one_point_oh": 1,
"dependent_projects": 6,
"dependent_repositories": 4,
"stars": 5,
"contributors": 2,
"subscribers": 1,
"all_prereleases": 0,
"any_outdated_dependencies": -1,
"is_deprecated": 0,
"is_unmaintained": 0,
"is_removed": 0
}
```

Note that some of these numbers are logarithmic, e.g. `+log(contributors)/2`

**Comment by zeke** [comment]
> what do you think of unifying the structure of each repo in repos-using-electron#lite to be the same as `repository` prop in `electron-npm-packages`?

In the long term I think this definitely makes sense, and will make it practical for us to share templates and code between "package results" and "repo results" as we implement faceted search results on electronjs.org (https://github.com/electron/electronjs.org/issues/864)

In the short term, though, I don't think we should copy the structure of `repository` from `electron-npm-packages`, as it is essentially a convenience object with the repo URL redundantly sliced and diced in different ways using [github-url-to-object](ghub.io/github-url-to-object).

> deciding which props to keep for the repo object.

SourceRank covers most (but not all) of the metrics mentioned on npms.io/about. Rather than re-inventing the wheel, let's give SourceRank a try and see how the results work for us. I opened https://github.com/electron/repos-using-electron/issues/25 where we can continue working on this.

@vanessayuenn now that tests are passing on this PR, I'm gonna ship it (just to GitHub, not npm). If it's missing something, let's iterate.

**Comment by vanessayuenn** [comment]
@zeke 😮 😮 the SourceRank algorithm explanation is fantastic! We can/should definitely look into using that for electronjs.org search, maybe for the next iteration. I am 👍 on shipping this as is for now and put more thought into restructuring the objects in the long run.

**Pull request merged**
