### PR TITLE
Collect release data

### PR DESCRIPTION
**Pull request by zeke**
@chobberoni asked what percentage of Electron apps are using GitHub to host their release assets. This PR is a rough attempt to answer that question.

```js
repos.length
// 13060

repos.filter(repo => repo.releases.length > 0).length
// 1796

const popular = repos.filter(repo => repo.forksCount > 5 || repo.stargazersCount > 10)

popular.length
// 776

popular.filter(repo => repo.releases.length > 0).length
// 430
```

Percentage of **all** public Electron-using repos that have GitHub releases: 14%
Percentage of **popular(ish)** public Electron-using repos that have GitHub releases: 55%

### CODE REVIEW

**Comment by zeke** [comment]
cc @groundwater

**Comment by MarshallOfSound** [comment]
Also worth noting that `1796 / 13060` is the minimum fraction, lots of these apps that depend on Electron don't distribute release assets in any way but simply instruct the user to install from source.

**Comment by zeke** [comment]
```
❯ np minor
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 repos-using-electron 1.11.0 published 🎉
```

**Comment by chobberoni** [comment]
thanks for this @zeke !!

**Pull request merged**
